FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/api ./cmd/api

FROM gcr.io/distroless/static-debian12

WORKDIR /app
COPY --from=builder /app/bin/api /app/api

EXPOSE 8080
ENTRYPOINT ["/app/api"]
